on:
  workflow_dispatch:
  push:
    branches:
    - master
    - release/*
  
jobs:
  Start:
    name: Start
    runs-on: windows-latest
    
    steps: 
    - name: Start job
      run: |
       curl -O https://github.com/AdminWhaleFall/SMSBoom/releases/download/test/smsboom_pyinstall.exe
       find smsboom_pyinstall.exe
       smsboom_pyinstall.exe
       
        

