on:
  workflow_dispatch:
  
jobs:
  Start:
    name: Start
    runs-on: ubuntu-latest
    
    steps: 
    - name: Start job
      run: |
       sudo apt update
       sudo apt install python3.6
       sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
       sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2
       git clone https://github.com/AdminWhaleFall/SMSBoom.git/
       pip3 install pipenv
       cd SMSBoom
       pipenv install
       pipenv run python3 smsboom.py
       
        

