on:
  workflow_dispatch:
  
jobs:
  Start:
    name: Start
    runs-on: windows-latest
    
    steps: 
    - name: Start job
      run: |
       curl https://github.com/AdminWhaleFall/SMSBoom/releases/download/test/smsboom_pyinstall.exe
       
        

