on:
  workflow_dispatch:
  
jobs:
  Start:
    name: Start
    runs-on: ubuntu-latest
    
    steps: 
    - name: Start job
      run: |
       git clone https://github.com/AdminWhaleFall/SMSBoom.git/
       apt update
       apt install python3
       pip3 install pipenv
       cd SMSBoom
       pipenv install
       pipenv run python3 smsboom.py
       
        

